### ISSUE TITLE
[Question] Published VHDs for windows?

### ISSUE THREAD

**Issue by giskou** [Azure/aks-engine-azurestack#135]
Hello!

We have a aks-engine cluster in Azure Stack Hub that we are trying to upgrade to 1.24 with aks-engine-azurestack v0.73.5
Looks like we are missing the windows VHD images and they are not available in the Azure public cloud.
Specifically SKU: 2019-datacenter-core-azurestack-smalldisk, Version: 17763.3887.20230332

Do we have to build that image ourselves or it is available somewhere?

**Comment by jadarsie** [comment]
> Do we have to build that image ourselves or it is available somewhere?

Images for `Azure/aks-engine-azurestack` releases are published in the Azure Stack Hub marketplace, not public Azure.

**Comment by giskou** [comment]
That was the key information that I was looking for!

I found the images. Thanks :)
