### ISSUE TITLE
Custom script extension fails on Master Node

### ISSUE THREAD

**Issue by cacarroll** [Azure/aks-engine-azurestack#141]
**Describe the bug**
The custom script extension for the master node never finalizes and errors. 

 {"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n
   \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-master-0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=30\\n[stdout]\\

**Steps To Reproduce**
{
    "apiVersion": "vlabs",
    "location": "local",
    "properties": {
        "orchestratorProfile": {
            "orchestratorRelease": "1.24",
            "orchestratorVersion": "1.24.11",
            "kubernetesConfig": {
                "cloudProviderBackoff": true,
                "cloudProviderBackoffRetries": 1,
                "cloudProviderBackoffDuration": 30,
                "cloudProviderRateLimit": true,
                "cloudProviderRateLimitQPS": 100,
                "cloudProviderRateLimitBucket": 150,
                "cloudProviderRateLimitQPSWrite": 25,
                "cloudProviderRateLimitBucketWrite": 30,
                "useCloudControllerManager": true,
                "useInstanceMetadata": false,
                "clusterSubnet": "172.24.128.0/17",
                "serviceCidr": "172.24.16.0/20",
                "dnsServiceIP": "172.24.16.10",
                "kubeletConfig": {
                    "--node-status-update-frequency": "1m"
                },
                "privateCluster": {
                    "enabled": true
                },
                "controllerManagerConfig": {
                    "--node-monitor-grace-period": "5m",
                    "--pod-eviction-timeout": "5m",
                    "--route-reconciliation-period": "1m"
                },
                "addons": [
                ]
            }
        },
        "customCloudProfile": {
            "portalURL": "https://portal.local.azurestack.external",
            "identitySystem": "adfs"
        },
        "featureFlags": {
            "enableTelemetry": false
        },
        "masterProfile": {"dnsPrefix":"tst9","vmSize":"Standard_DS2_v2","distro":"aks-ubuntu-20.04","vnetSubnetId":"/subscriptions//resourceGroups/tst9-spk-rg/providers/Microsoft.Network/virtualNetworks/tst9-spk-vnet/subnets/controlPlane-sn","count":3,"firstConsecutiveStaticIP":"172.24.0.239"},
        "agentPoolProfiles": [{"name":"agentpool","AcceleratedNetworkingEnabled":false,"vmSize":"Standard_DS2_v2","distro":"aks-ubuntu-20.04","vnetSubnetId":"/subscriptions//resourceGroups/tst9-spk-rg/providers/Microsoft.Network/virtualNetworks/tst9-spk-vnet/subnets/agents-sn","count":3,"availabilityProfile":"AvailabilitySet"}],
        "linuxProfile": {
            "adminUsername": "azureuser",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData": ""
                    }
                ]
            },
            "runUnattendedUpgradesOnBootstrap": false,
            "enableUnattendedUpgrades": false
        },
        "servicePrincipalProfile": {
            "clientId": "",
            "secret": ""
        }
    }
}

**Expected behavior**

**AKS Engine version**
.76
**Kubernetes version**

**Additional context**

**Comment by jadarsie** [comment]
`/var/log/azure/cluster-provision.log` is usually more helpful

**Comment by cacarroll** [comment]
I do see some TLS errors. 
[cluster-provision.log](https://github.com/Azure/aks-engine-azurestack/files/11519499/cluster-provision.log)

**Comment by jadarsie** [comment]
I do not see anything obvious.
If you have access to product support, please contact them.
Otherwise, please provide more symptoms to narrow the search space.
If you are on an ASDK, you may be resource-constraint.
