### ISSUE TITLE
Master Nodes from 3 VMs to 1 VM & Node Pool Deletion - Azure Stack Hub

### ISSUE THREAD

**Issue by zohebk8s** [Azure/aks-engine-azurestack#152]
Hi Team,

Currently we have deployed Azure Stack Hub using AKS engine and it’s up and running with 3 Master VMs and few node pools.

However we wanted to reduce the master nodes from 3 VMs to 1 VM and we want to delete one node pool as well.

Is it possible to reduce the master VMs from 3 to 1 ? And nodepool deletion too

**Comment by jadarsie** [comment]
There are no commands to perform these actions. It is possible, but you have to do it yourself.

1 master node is not recommended nor supported. However, if you insist, the key is updating the etcd configuration.

To delete a node pool, you have to drain the nodes to remove, delete their corresponding IaaS resources, delete the node resource (`kubectl delete no <name>`) and update the API model to reflect the new cluster state.

Word of caution. These steps are off the top of my head, I did not validate them.

**Comment by zohebk8s** [comment]
@jadarsie Thanks for sharing valuable information.
