### ISSUE TITLE
Pod in crashloopbackoff state after k8s upgrade to 1.21.10

### ISSUE THREAD

**Issue by Shamsun1** [Azure/aks-engine-azurestack#67]
**Describe the bug**
When upgrading from kubernetes version 1.20.11 to 1.21.10 the apimodel is updated to enable the azuredisk-csi-driver. An existing grafana applications PV and PVC were migrated to use the new azure disk csi provider and the pod was running successfully. When an other grafana instance with a PV and PVC was deployed using the disk.csi.azure.com provisioner and "managed-premium" class, the pod went into a "CrashLoopBackOff" state. 

A new storage class was then created and the "fsType" parameter set to "ext4". An additional grafana app was deployed successfully using this new storage class. Is there a way to set the fsType parameter for existing storage classes and why does creating a new storage class with the fsType set seem to resolve the issue with the pod? 

**Steps To Reproduce**
Upgrade AKS cluster from 1.20.11 to 1.21.10

**Expected behavior**
Application should deploy successfully using the existing storage classes.

**AKS Engine version**
Upgrade from 0.67.3 to 0.70.0

**Kubernetes version**
Upgrade from 1.20.11 to 1.21.10

**Additional context**

**Comment by jadarsie** [comment]
Hello @Shamsun1, need some extra info/clarifications:

What's the difference between the working and not working deployments? Same CSI driver, different StorageClass? Which StorageClass was used in case 1?

```
1. An existing grafana applications PV and PVC were migrated to use the new azure disk csi provider and the pod was running successfully.
2. When an other grafana instance with a PV and PVC was deployed using the disk.csi.azure.com provisioner and "managed-premium" class, the pod went into a "CrashLoopBackOff" state.
```

How do you tell that the problem here is storage?
```
[...] the pod went into a "CrashLoopBackOff" state
```

Could you please share your SC definition?
```
A new storage class was then created and the "fsType" parameter set to "ext4".
```

No, but you can create your own SC
```
Is there a way to set the fsType parameter for existing storage classes?
```

`ext4` is the default value for `fsType`, my guess is that `fsType` alone did not solve your problem
```
why does creating a new storage class with the fsType set seem to resolve the issue with the pod?
```

**Comment by Shamsun1** [comment]
@jadarsie
> ``` 
>What's the difference between the working and not working deployments? Same CSI driver, different StorageClass? Which StorageClass was used in case 1?
The CSI driver is the same but the storage class was different. Case 1 used the "managed-premium" storage class but deploying a new app with the same storage class and driver also resulted in the same issue.

> ```
> 1. An existing grafana applications PV and PVC were migrated to use the new azure disk csi provider and the pod was running successfully.
> 2. When an other grafana instance with a PV and PVC was deployed using the disk.csi.azure.com provisioner and "managed-premium" class, the pod went into a "CrashLoopBackOff" state.
> ```
>
>How do you tell that the problem here is storage?

The CSI driver was deleted and recreated with the fsGroupPolicy set to File which seems to solve the issue. By default this value was set to ReadWriteOnceWithFSType. 

> ```
> Could you please share your SC definition?
`apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dxcastorageclass
parameters:
  fsType: ext4
  cachingMode: ReadOnly
  kind: managed
  skuName: Premium_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true`

> ```
> `ext4` is the default value for `fsType`, my guess is that `fsType` alone did not solve your problem
When performing the PV migration the fsType of the existing PV was blank. The existing storageclasses do not have an fsType defined. Does this default to ext4 even if no value is defined?

**Comment by jadarsie** [comment]
Thx @Shamsun1, I think `fsGroupPolicy` is the key here. From [CSI docs](https://kubernetes-csi.github.io/docs/support-fsgroup.html):

`ReadWriteOnceWithFSType: Indicates that volumes will be examined to determine if volume ownership and permissions should be modified to match the pod's security policy. Changes will only occur if the **fsType is defined** and the persistent volume's accessModes contains ReadWriteOnce. .`

Setting `fsType` explicitly should allow the driver to modify the PV permissions (assuming `ReadWriteOnce` access mode). Changing the AKS Engine's default for `fsGroupPolicy` to `File` will require more time as we need to understand if/what side effects has for existing users.

Remember that you can also choose to disable the addon on the API Model and [manually deploy](https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#1-install-azure-disk-csi-driver-manually) the CSI driver through Helm. This option gives you total control in exchange of extra operational effort.

**Comment by Shamsun1** [comment]
@jadarsie We are looking to continue using the existing storage classes for our applications. We attempted to modify the azure-cloud-provider addon in the kubernetesConfig to use a custom yaml where the fsType is set to ext4 but this would not apply. We could however set the fsType to ext4 by editing the storage classes in azure-cloud-provider.yaml on the master nodes. Is it possible to backport the storage class fstype change into aks engine 0.70.0?
