### ISSUE TITLE
Setting fsType to ext4 in default storage classes

### ISSUE THREAD

**Issue by Shamsun1** [Azure/aks-engine-azurestack#91]
**Describe the bug**
We are looking to continue using the existing storage classes for our applications. We attempted to modify the azure-cloud-provider addon in the API model to use a custom yaml where the fsType for the default storage classes was set to ext4 but this would not apply. We could however set the fsType to ext4 by editing the storage classes in azure-cloud-provider.yaml on all of the master nodes.

**Steps To Reproduce**
An application with a PVC and PV was deployed into a cluster running kubernetes v1.20.11 and AKS engine v0.67.3. The cluster was then upgraded to kubernetes 1.21.10 and the persistent volume/persistent volume claim were migrated from the "in-tree" provider to the azure disk csi provider. The application remains in a "ContainerCreating" state until the storage class fsType is set to ext4.  

**Expected behavior**
We would expect apps using the existing storage classes to continue functioning after the upgrade to kubernetes 1.21.10 and migration to the azure disk csi provider or for there to be a way of setting the fsType for the default storage classes. Is it possible to get the storage class fstype change made to azure-cloud-provider.yaml in v0.75.3 backported into AKS engine v0.70.0? Or is there a recommended approach for setting the fsType for the storage classes?

**AKS Engine version**
Upgrading from AKSE v0.67.3 to v0.70.0

**Kubernetes version**
Upgrading from v1.20.11 to v1.21.10

**Additional context**
Related to #73

**Comment by jadarsie** [comment]
Hello @Shamsun1, please contact support, we will work with them to plan how to take you to one of the AKS Engine supported versions.
